// Every element the UI touches, looked up once. Other modules import `el`
// instead of calling getElementById themselves.

export const el = {
  loadingScreen: document.getElementById("loading-screen"),
  loginScreen: document.getElementById("login-screen"),
  appScreen: document.getElementById("app-screen"),
  signInBtn: document.getElementById("sign-in-btn"),
  signOutBtn: document.getElementById("sign-out-btn"),
  shuffleViewBtn: document.getElementById("shuffle-view-btn"),
  searchBtn: document.getElementById("search-btn"),
  playlistsBtn: document.getElementById("playlists-btn"),
  settingsBtn: document.getElementById("settings-btn"),

  breadcrumb: document.getElementById("breadcrumb"),
  fileList: document.getElementById("file-list"),
  pullRefresh: document.getElementById("pull-refresh"),
  statusMsg: document.getElementById("status-msg"),

  topBar: document.getElementById("top-bar"),
  selectToggleBtn: document.getElementById("select-toggle-btn"),
  selectHeaderBar: document.getElementById("select-header-bar"),
  selectHeaderLabel: document.getElementById("select-header-label"),
  selectCancelBtn: document.getElementById("select-cancel-btn"),
  selectAllBtn: document.getElementById("select-all-btn"),
  selectActionBar: document.getElementById("select-action-bar"),
  selectCountLabel: document.getElementById("select-count-label"),
  selectAddPlaylistBtn: document.getElementById("select-add-playlist-btn"),
  selectAddQueueBtn: document.getElementById("select-add-queue-btn"),
  selectShuffleBtn: document.getElementById("select-shuffle-btn"),

  searchOverlay: document.getElementById("search-overlay"),
  searchInput: document.getElementById("search-input"),
  searchCloseBtn: document.getElementById("search-close-btn"),
  searchResults: document.getElementById("search-results"),

  playlistsOverlay: document.getElementById("playlists-overlay"),
  playlistsCloseBtn: document.getElementById("playlists-close-btn"),
  newPlaylistBtn: document.getElementById("new-playlist-btn"),
  playlistsList: document.getElementById("playlists-list"),

  settingsOverlay: document.getElementById("settings-overlay"),
  settingsCloseBtn: document.getElementById("settings-close-btn"),
  libraryRootLabel: document.getElementById("library-root-label"),
  changeFolderBtn: document.getElementById("change-folder-btn"),
  rescanLibraryBtn: document.getElementById("rescan-library-btn"),
  resetLibraryBtn: document.getElementById("reset-library-btn"),
  backupBtn: document.getElementById("backup-btn"),
  shareBackupBtn: document.getElementById("share-backup-btn"),
  restoreBtn: document.getElementById("restore-btn"),
  restoreFileInput: document.getElementById("restore-file-input"),
  scanStatus: document.getElementById("scan-status"),
  themeList: document.getElementById("theme-list"),
  appVersionLabel: document.getElementById("app-version-label"),
  loginVersionLabel: document.getElementById("login-version-label"),
  showIntroBtn: document.getElementById("show-intro-btn"),
  errorLogBtn: document.getElementById("error-log-btn"),

  introOverlay: document.getElementById("intro-overlay"),
  introBackBtn: document.getElementById("intro-back-btn"),
  introNextBtn: document.getElementById("intro-next-btn"),
  introRestoreBtn: document.getElementById("intro-restore-btn"),
  introFinishBtn: document.getElementById("intro-finish-btn"),

  errorLogOverlay: document.getElementById("error-log-overlay"),
  errorLogBackBtn: document.getElementById("error-log-back-btn"),
  errorLogCopyBtn: document.getElementById("error-log-copy-btn"),
  errorLogClearBtn: document.getElementById("error-log-clear-btn"),
  errorLogList: document.getElementById("error-log-list"),

  detailOverlay: document.getElementById("detail-overlay"),
  detailBackBtn: document.getElementById("detail-back-btn"),
  detailTitle: document.getElementById("detail-title"),
  detailList: document.getElementById("detail-list"),
  detailHeaderActions: document.getElementById("detail-header-actions"),
  detailPlayBtn: document.getElementById("detail-play-btn"),
  detailShuffleBtn: document.getElementById("detail-shuffle-btn"),

  folderPickerOverlay: document.getElementById("folder-picker-overlay"),
  folderPickerHeading: document.getElementById("folder-picker-heading"),
  folderPickerCancelBtn: document.getElementById("folder-picker-cancel-btn"),
  fpHomeBtn: document.getElementById("fp-home-btn"),
  fpBreadcrumb: document.getElementById("fp-breadcrumb"),
  fpFileList: document.getElementById("fp-file-list"),
  fpUseHereBtn: document.getElementById("fp-use-here-btn"),

  toast: document.getElementById("toast"),

  nowPlayingBar: document.getElementById("now-playing-bar"),
  npArt: document.querySelector(".np-art"),
  miniArt: document.getElementById("mini-art"),
  miniArtFallback: document.getElementById("mini-art-fallback"),
  nowPlayingTitle: document.getElementById("now-playing-title"),
  nowPlayingArtist: document.getElementById("now-playing-artist"),
  miniPrevBtn: document.getElementById("mini-prev-btn"),
  miniPlayPauseBtn: document.getElementById("mini-play-pause-btn"),
  miniNextBtn: document.getElementById("mini-next-btn"),

  fullPlayer: document.getElementById("full-player"),
  fullPlayerCloseBtn: document.getElementById("full-player-close-btn"),
  upNextBtn: document.getElementById("up-next-btn"),
  addToPlaylistBtn: document.getElementById("add-to-playlist-btn"),
  lyricsBtn: document.getElementById("lyrics-btn"),
  lyricsPanel: document.getElementById("lyrics-panel"),
  fullPlayerArt: document.querySelector(".full-player-art"),
  fullArt: document.getElementById("full-art"),
  fullArtFallback: document.getElementById("full-art-fallback"),
  fullTitle: document.getElementById("full-title"),
  fullArtist: document.getElementById("full-artist"),
  fullSeekBar: document.getElementById("full-seek-bar"),
  fullCurrentTime: document.getElementById("full-current-time"),
  fullDuration: document.getElementById("full-duration"),
  shuffleBtn: document.getElementById("shuffle-btn"),
  fullPrevBtn: document.getElementById("full-prev-btn"),
  fullPlayPauseBtn: document.getElementById("full-play-pause-btn"),
  fullNextBtn: document.getElementById("full-next-btn"),
  repeatBtn: document.getElementById("repeat-btn"),

  addPlaylistModal: document.getElementById("add-playlist-modal"),
  addPlaylistList: document.getElementById("add-playlist-list"),
  addPlaylistNewBtn: document.getElementById("add-playlist-new-btn"),
  addPlaylistCancelBtn: document.getElementById("add-playlist-cancel-btn"),

  folderActionsModal: document.getElementById("folder-actions-modal"),
  folderActionsTitle: document.getElementById("folder-actions-title"),
  folderPlayBtn: document.getElementById("folder-play-btn"),
  folderAddQueueBtn: document.getElementById("folder-add-queue-btn"),
  folderAddPlaylistBtn: document.getElementById("folder-add-playlist-btn"),
  folderActionsCancelBtn: document.getElementById("folder-actions-cancel-btn"),

  playlistActionsModal: document.getElementById("playlist-actions-modal"),
  playlistActionsTitle: document.getElementById("playlist-actions-title"),
  playlistRenameBtn: document.getElementById("playlist-rename-btn"),
  playlistDeleteBtn: document.getElementById("playlist-delete-btn"),
  playlistClearBtn: document.getElementById("playlist-clear-btn"),
  playlistActionsCancelBtn: document.getElementById("playlist-actions-cancel-btn"),

  upNextOverlay: document.getElementById("up-next-overlay"),
  upNextCloseBtn: document.getElementById("up-next-close-btn"),
  upNextNowLabel: document.getElementById("up-next-now-label"),
  upNextNowRow: document.getElementById("up-next-now-row"),
  upNextList: document.getElementById("up-next-list"),
};