// Copies the site's actual source files (repo root — same origin GitHub Pages
// serves from) into www/ for Capacitor to bundle. Keeps the repo root as the
// single source of truth; www/ is a disposable, gitignored build artifact
// regenerated by this script before every `cap sync`.
import { cpSync, rmSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const wwwDir = join(here, "www");

// Same file list as sw.js's SHELL_FILES — this app shell is what gets shipped.
const ENTRIES = ["index.html", "css", "js", "manifest.json", "icons", "sw.js"];

rmSync(wwwDir, { recursive: true, force: true });
mkdirSync(wwwDir, { recursive: true });

for (const entry of ENTRIES) {
  cpSync(join(repoRoot, entry), join(wwwDir, entry), { recursive: true });
}

console.log(`Synced ${ENTRIES.length} entries from repo root into ${wwwDir}`);
